#!/usr/bin/env perl

use strict;
use warnings;
use open ':std', IO => ':utf8'; # all is utf8!

use Getopt::Long;
use Text::Lossy;

my @filters = ();

GetOptions(
    'filter=s' => \@filters, 
) or exit(1);

# Multiple filters, in-order
@filters = split(qr{ , }xms, join(',', @filters));

my $lossy = Text::Lossy->new();
$lossy->add( @filters );

while (my $line = <>) {
    $line = $lossy->process($line);
    print $line;
}
# We add a newline at the very very end, just to be nice
print "\n";
